---
- name: Setup Ansible
  hosts: 
    - 34.192.151.138
    - 44.198.105.77
    - 52.207.158.23
    - 54.92.233.212
    - 204.236.226.148
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes
    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Add apt
      shell: "sudo add-apt-repository --yes --update ppa:ansible/ansible"
      args:
        executable: /bin/bash

    - name: Install Ansible
      apt:
        name: "{{item}}"
        state: present
      loop:
        - software-properties-common
        - ansible
