---
- name: Setup Frontend & Backend
  hosts: 44.198.105.77
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Remove current apps
      shell: "sudo rm -r backendsound dumbsound"
      args:
        executable: /bin/bash
        
    - name: Clone Dumplay Apps
      shell: "git clone https://github.com/ogak/dumbplay-frontend.git dumbsound"
      args:
        executable: /bin/bash
    
    - name: Clone Backend Apps
      shell: "git clone https://github.com/ogak/dumbplay-backend.git backendsound"
      args:
        executable: /bin/bash

    - name: Install python-pip
      apt:
        name: python-pip
        state: present
    
    - name: Pip install docker
      shell: pip install docker
      args:
        executable: /bin/bash

    - name: Log into DockerHub
      community.docker.docker_login:
        username: ogak
        password: MyDockerId171

    # - name: Docker build frontend step 1
    #   shell: cd dumbsound
    #   args:
    #     executable: /bin/bash

    # - name: Docker build frontend step 2
    #   shell: "docker build -t ogak/dumbsound:1.1 ."
    #   args:
    #     executable: /bin/bash

    # - name: Docker build frontend step 3
    #   shell: cd 
    #   args:
    #     executable: /bin/bash
    
    # - name: Docker build backend step 1
    #   shell: cd backendsound
    #   args:
    #     executable: /bin/bash
    
    # - name: Docker build backend step 2
    #   shell: "docker build -t ogak/backend:1.3 ."
    #   args:
    #     executable: /bin/bash
    
    # - name: Docker build backend step 3
    #   shell: cd 
    #   args:
    #     executable: /bin/bash
    
    - name: Docker pull frontend
      shell: docker pull ogak/dumbsound:1.1
      args:
        executable: /bin/bash
    
    - name: Docker pull backend
      shell: docker pull ogak/backendsound:1.3
      args:
        executable: /bin/bash
    
    - name: Install Dumbplay apps (Dumbsound)
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d" 
        chdir: /home/ubuntu/dumbsound/