---
- name: Setup Docker & Docker Compose
  hosts: 
    - 34.192.151.138
    - 44.198.105.77
    - 52.207.158.23
    - 54.92.233.212
    - 204.236.226.148
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Setup repository
      shell: "sudo apt-get install ca-certificates curl gnupg lsb-release"
      args:
        executable: /bin/bash
    
    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Update system
      apt:
        update_cache: yes
    
    - name: Install docker engine
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
   
    - name: Install stable release docker compose
      shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        executable: /bin/bash

    # - name: Install docker compose
    #     url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
    #     dest: /usr/local/bin/docker-compose
    #     return_content: true
    #     follow_redirects: all
    #     validate_certs: true
    
    - name: Apply executable permission to the binary
      shell: "sudo chmod +x /usr/local/bin/docker-compose"
      args:
        executable: /bin/bash
    
    - name: Remove sudo on docker command
      shell: sudo usermod -aG docker ubuntu
      args:
        executable: /bin/bash