---
- name: Setup Nginx
  hosts: 34.192.151.138
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes
    - name: Upgrade system
      apt:
        upgrade: dist
    
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
