---
- name: Setup Node exporter
  hosts: 
    - 34.192.151.138
    - 44.198.105.77
    - 52.207.158.23
    - 54.92.233.212
    - 204.236.226.148
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Download node exporter
      shell: "wget https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
      args:
        executable: /bin/bash
    
    - name: Extract node exporter
      shell: "tar xvfz node_exporter-1.2.2.linux-amd64.tar.gz"
      args:
        executable: /bin/bash
    
    - name: Move node exporter to /usr/local/bin
      shell: sudo mv node_exporter-1.2.2.linux-amd64/node_exporter /usr/local/bin
      args:
        executable: /bin/bash
    
    - name: Add user node exporter
      shell: sudo useradd -rs /bin/false node_exporter
      args:
        executable: /bin/bash
    
    - name: Copy node_exporter.service file
      copy:
        src: files/node_exporter.service 
        dest: /etc/systemd/system/

    - name: Daemon-reload
      shell: sudo systemctl daemon-reload
      args:
        executable: /bin/bash
    
    - name: Enable node exporter
      shell: sudo systemctl enable node_exporter
      args:
        executable: /bin/bash
    
    - name: Start node exporter
      shell: sudo systemctl start node_exporter
      args:
        executable: /bin/bash