---
- name: Setup CI/CD Jenkins Docker
  hosts: 54.92.233.212
  become: true
  tasks:
    - name: Copy docker compose
      copy:
        src: docker-jenkins
        dest: /home/ubuntu/
    
    - name: Initialize data
      shell: cd docker-node-exporter
      args:
        executable: /bin/bash

    - name: Run docker compose
      shell: "docker-compose up -d"
      args:
        executable: /bin/bash