---
global:
  scrape_interval: 10m

scrape_configs:
  - job_name: "prometheus-metrics"
    scrape_interval: 5m
    static_configs:
      - targets: ['204.236.226.148:9100']
  - job_name: "node_exporter_metrics"
    scrape_interval: 5m
    scrape_timeout: 1m
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['44.198.105.77:9100','34.192.151.138:9100','52.207.158.23:9100','54.92.233.212:9100']